### ISSUE TITLE
buddypress/members/template-profile.php does not return $achievement->badge_id

### ISSUE THREAD

**Issue by mediaformat** [DigitalPygmalion/badge-factor-theme#1]
Since refactor of [get_user_achievements()](https://github.com/DigitalPygmalion/badge-factor/commit/4a6deec6fa17c5cabae72e08a61affde6085b016)
`$achievement->badge_id` does not exist, 
`achievement` returns badge post_type, not the achievement.

**Comment by danidou** [comment]
This problem has been fixed by using $achievement->ID instead.
